name: CI Build Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Docker image
        run: |
          docker build -t my-app .
      - name: Push Docker image to registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag my-app my-dockerhub-username/my-app:latest
          docker push my-dockerhub-username/my-app:latest
      